### ISSUE TITLE
Choose Project Idea

### ISSUE THREAD

**Issue by shafkat008** [shafkat008/Capstone-Project#1]

**Comment by shafkat008** [comment]
Currently have these ideas lined up to choose from-

1.  Dr. Al-Anbagi's EV charging
2.  Joshua's Solar power
3. Shaheer's waste management
4. E-Tap software

More ideas would be introduced to us by the faculty in the coming days.

**Comment by shafkat008** [comment]
Discussed project ideas yesterday with Dr. Al-Anbagi.

1.  Solar Powered EV charging station - Output would be physical LEDs indicating whether the station is being used for charging or idle, also would be deployed in a simple website to access the status from phone/laptop.

Dr. Al-Anbagi already has these devices to utilize for this project

E-gauge: https://www.egauge.net/media/support/docs/eg4115-datasheet.pdf
Current Transformer

2. Any IoT project: Floor is open to us to choose based on current world problems

**Comment by shaheerhasan21** [comment]
we talked with irfan today 
1. he showed us the program that runs the solar panel grid, he said that the system does not show the battery level and does not allow a user to book the parking station
2. 
3.

**Comment by typicaljosh** [comment]
Discussed with Dr. Laforge about a stand-alone charging station:  

overview:
solar panel -> DC-to-AC -> charging station 
any excess power will be distributed elsewhere

**Comment by shafkat008** [comment]
Today we discussed with multiple professors to suggest a project idea -

1. Dr. Bais would let us know if he comes up with an idea in the coming days
2.  Dr. Wang setup a meeting on Friday to discuss about a BMS project
3.  Dr. Paranjape suggested two ideas he would like someone to take on - Self Driving Wheelchair and Dynamic Video Capture
